### ISSUE TITLE
record.type issue

### ISSUE THREAD

**Issue by OwenArnold** [DMSC-Instrument-Data/mantid-algorithm-usage#1]
Running this

```
$python3 merge_data.py 
```

I get to about 30 algorithms then:

```
Traceback (most recent call last):
  File "merge_data.py", line 115, in add_line_count_info
    test_lines = get_file_length(testsource)
UnboundLocalError: local variable 'testsource' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "merge_data.py", line 375, in <module>
    merged = merge()
  File "merge_data.py", line 162, in merge
    add_line_count_info(item)
  File "merge_data.py", line 121, in add_line_count_info
    eprint('Failed to open test source ' + testsource)
UnboundLocalError: local variable 'testsource' referenced before assignment
```

I think this happens because a `record.type` comes out as being neither c++ or Python. Version of Python is 3.4.3 on OSX.

**Comment by SimonHeybrock** [comment]
@OwenArnold This looks weird indeed. In fact I am surprised why it works on my machine. Could you check if this fixes your issue.

**Comment by OwenArnold** [comment]
@SimonHeybrock. Yes this fixes it 👍
